name: GEIGERARTS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.42265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0500'
    - '#bc9848'
    - '#d7bf7e'
    - '#9d6e2e'
    - '#804920'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
