name: GEIGERARTS
favicon: null
layout_spectrum: 0.44088864838704467
typography_spectrum: 0.49182023690082133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.89452921343036
  lightness: 0.627827811986208
  saturation: 0.45682456786744297
  rhythmicContrast: 0.6035557915456593
purpose: []
